services:
  nginx:
    image: nginx:latest
    container_name: lamp-nginx
    ports:
      - "8080:80"  
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apache
    networks:
      - lamp-network 
      
  apache:
    image: php:8.2-apache
    container_name: lamp-apache
    restart: always  # Auto-restart on crash
    volumes:
      - ./src/www:/var/www/html
      - ./.env:/var/www/.env
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - lamp-network
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: lamp-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/db-init:/docker-entrypoint-initdb.d
    networks:
      - lamp-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: lamp-phpmyadmin
    ports:
      - "8081:80"
    env_file:
      - .env
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASS}
    depends_on:
      - mysql
    networks:
      - lamp-network



networks:
  lamp-network:
    driver: bridge

volumes:
  mysql-data: